#!/usr/bin/env bash
set -euo pipefail

# Generate the NASM names consumed by the kernel from the reviewable TSV
# contracts.  The output is deliberately deterministic so the parity gate can
# reject stale checked-in constants.
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
OUT=${1:-"$ROOT/kernel/self_hosting_abi.inc"}
python3 - "$ROOT" "$OUT" <<'PY'
import csv
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])

def read_tsv(path, expected):
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle, delimiter="\t"))
    if list(rows[0]) != expected if rows else True:
        raise SystemExit(f"{path}: unexpected header")
    return rows

syscalls = read_tsv(
    root / "contracts/self-hosting-alpha/syscall-abi-v1.tsv",
    ["selector", "name", "result"],
)
imports = read_tsv(
    root / "contracts/self-hosting-alpha/gwo2-import-abi-v1.tsv",
    ["import_id", "name", "argc", "result", "syscall_selector"],
)

def ident(value):
    # Syscall rows may carry an ABI argument annotation after the function
    # name; the symbol must remain stable when that annotation is refined.
    base = value.split("(", 1)[0]
    return re.sub(r"[^A-Za-z0-9]+", "_", base).strip("_").upper()

lines = [
    "; generated by scripts/generate_self_hosting_abi.sh; do not edit",
    "; source: contracts/self-hosting-alpha/*.tsv",
    "",
    "; syscall selectors",
]
for row in syscalls:
    selector = row["selector"]
    if not re.fullmatch(r"0x[0-9a-fA-F]{2}", selector):
        raise SystemExit(f"invalid syscall selector: {selector}")
    lines.append(f"%define SYS_{ident(row['name'])} {selector.lower()}")
lines += ["", "; GWO2 import identifiers"]
for row in imports:
    if not row["import_id"].isdigit():
        raise SystemExit(f"invalid import id: {row['import_id']}")
    lines.append(f"%define GWO_IMPORT_{ident(row['name'])} {row['import_id']}")
lines.append("")
text = "\n".join(lines)
if not text.endswith("\n"):
    text += "\n"
if str(out) == "-":
    sys.stdout.write(text)
else:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8", newline="\n")
PY
